logging:
  level:
    root: warn
    '[com.evanjon.studySpring]': info

server:
  servlet:
    session:
      timeout: 15m

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  sql:
    init:
      platform: postgresql
      mode: never
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

app:
  origin: "localhost:8080"
